### ISSUE TITLE
Weird pauses and jumps in the video

### ISSUE THREAD

**Issue by ChristophHaag** [pontostroy/gstreamer-screenrecording#3]
Example: https://www.youtube.com/watch?v=9dERLwSVJS4

Recorded with vaapi: `gstreamer-screenrecording -s -n=v`

Wild guess: It could have something to do with the sound? It runs normally through the pauses...

Probably not an issue on your side, but I still made it to ask whether you can reproduce it or have seen anything like it.

**Comment by pontostroy** [comment]
how many minutes of recording is going on?

**Comment by ChristophHaag** [comment]
What do you mean? I recorded the 9:34 minutes that can be seen on youtube. I don't know whether it matches exactly with the time I recorded.

The first video hangs can be seen at 0:08 and 0:43, each about 2 seconds. Then there's a long one at 1:18-1:44 and another longe one from 2:18-2:34 (without sound?), then 3:08-3:18 and 3:54-4:01 with sound, then 4:34-4:50 without sound, 5:39-5:46, 6:18-6:47, 7:24-7:41, 8:14-8:27, 8:59-9:02.

I thought I saw random jumps in the video, but on youtube I don't see them. Maybe they were only in the source files. Maybe the files are corrupted in some way?

This only happens since recently. Maybe an update is at fault, or maybe it happens because I enabled intel tearfree...

**Comment by ChristophHaag** [comment]
I think this has mostly solved itself.

My guess is that it had to do with sna/dri3 in xf86-video-intel, but it's just a guess.
